" Vim color file - ciplogic
" Generated by http://bytefluent.com/vivify 2020-01-03
if version > 580
	hi clear
	if exists("syntax_on")
		syntax reset
	endif
endif

function! SetLightColors()
  " -------------------------------------------------------------------------
  " gray
  " -------------------------------------------------------------------------
  hi Comment guifg=#5f5f5f guibg=NONE guisp=NONE gui=NONE ctermfg=59 ctermbg=NONE cterm=NONE
  hi Statement guifg=#000000 guibg=NONE guisp=NONE gui=bold ctermfg=16 ctermbg=NONE cterm=bold
  hi Include guifg=#000000 guibg=NONE guisp=NONE gui=bold ctermfg=16 ctermbg=NONE cterm=bold

  " -------------------------------------------------------------------------
  " green
  " -------------------------------------------------------------------------
  hi Constant guifg=#008700 guibg=NONE guisp=NONE gui=NONE ctermfg=28 ctermbg=NONE cterm=NONE
  hi Special guifg=#008700 guibg=NONE guisp=NONE gui=bold ctermfg=28 ctermbg=NONE cterm=bold

  " -------------------------------------------------------------------------
  " blue
  " -------------------------------------------------------------------------
  hi Identifier guifg=#005f5f guibg=NONE guisp=NONE gui=bold ctermfg=23 ctermbg=NONE cterm=bold
  hi pythonAttribute guifg=#005f5f guibg=NONE guisp=NONE gui=bold ctermfg=23 ctermbg=NONE cterm=bold

  " -------------------------------------------------------------------------
  " yellow
  " -------------------------------------------------------------------------
  hi PreProc guifg=#ff8700 guibg=NONE guisp=NONE gui=bold ctermfg=208 ctermbg=NONE cterm=bold

  " -------------------------------------------------------------------------
  " red
  " -------------------------------------------------------------------------

  " -------------------------------------------------------------------------
  " Languages
  " -------------------------------------------------------------------------
  hi yamlBlockCollectionItemStart guifg=#008700 guibg=NONE guisp=NONE gui=NONE ctermfg=28 ctermbg=NONE cterm=NONE
endfunction

function! SetDarkColors()
  " -------------------------------------------------------------------------
  " gray
  " -------------------------------------------------------------------------
  hi Comment guifg=#5f5f5f guibg=NONE guisp=NONE gui=NONE ctermfg=59 ctermbg=NONE cterm=NONE
  hi Statement guifg=#ffffff guibg=NONE guisp=NONE gui=bold ctermfg=231 ctermbg=NONE cterm=bold
  hi Include guifg=#afafaf guibg=NONE guisp=NONE gui=bold ctermfg=145 ctermbg=NONE cterm=bold

  " -------------------------------------------------------------------------
  " green
  " -------------------------------------------------------------------------
  hi Constant guifg=#008700 guibg=NONE guisp=NONE gui=NONE ctermfg=28 ctermbg=NONE cterm=NONE
  hi Special guifg=#008700 guibg=NONE guisp=NONE gui=bold ctermfg=28 ctermbg=NONE cterm=bold

  " -------------------------------------------------------------------------
  " blue
  " -------------------------------------------------------------------------
  hi Identifier guifg=#0087af guibg=NONE guisp=NONE gui=NONE ctermfg=31 ctermbg=NONE cterm=NONE
  hi pythonAttribute guifg=#0087af guibg=NONE guisp=NONE gui=bold ctermfg=31 ctermbg=NONE cterm=bold

  " -------------------------------------------------------------------------
  " yellow
  " -------------------------------------------------------------------------
  hi PreProc guifg=#ff8700 guibg=NONE guisp=NONE gui=bold ctermfg=208 ctermbg=NONE cterm=bold

  " -------------------------------------------------------------------------
  " red
  " -------------------------------------------------------------------------
  hi yamlBlockCollectionItemStart guifg=#008700 guibg=NONE guisp=NONE gui=NONE ctermfg=28 ctermbg=NONE cterm=NONE
endfunction

set t_Co=256

if &g:background=="light"
    call SetLightColors()
else
    call SetDarkColors()
endif

let g:colors_name = "ciplogic"

