
call plug#begin('~/.vim/plugged')

" core init:
Plug 'file://.vim/plugged/AAAciplogic'

" Cool feature plugins
Plug 'vim-scripts/guicolorscheme.vim'  " 256 color support
Plug 'bling/vim-airline'               " cooler status bar
Plug 'bmustiata/ultisnips'             " UltiSnips, with no nested scripts
Plug 'brooth/far.vim'                  " Replace across multiple files
Plug 'scrooloose/nerdcommenter'    " Comment sections of code <leader>cc
Plug 'ntpeters/vim-better-whitespace'  " Whitespace highlight at the end, and chars
Plug 'bmustiata/vim-todo'              " TODO lists created with ease
Plug 'vim-scripts/DirDiff.vim'         " Diff two folders
Plug 'junegunn/vim-easy-align'         " Align markdown tables using EasyAlign

" Better writing
Plug 'reedes/vim-wordy'                " Wordy - check texts for bad writing
Plug 'rhysd/vim-grammarous'            " more write checks
Plug 'dbmrq/vim-ditto'                 " Check for repeated usage of woards

" source control
Plug 'airblade/vim-gitgutter'          " Git margins
Plug 'tpope/vim-fugitive'              " Git integrations

" Navigation
Plug 'scrooloose/nerdtree'             " NERDTree, basic navigation
Plug 'ctrlpvim/ctrlp.vim'              " Fuzzy navigate buffers, and files
Plug 'dkprice/vim-easygrep'            " Grep across multiple files <leader>vv

" languages support
Plug 'vim-test/vim-test'
Plug 'vim-scripts/ingo-library'
Plug 'vim-scripts/SyntaxRange'
Plug 'posva/vim-vue'
Plug 'solarnz/thrift.vim'
Plug 'bmustiata/vim-uc4'
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
Plug 'rust-lang/rust.vim'
Plug 'leafgarland/typescript-vim'
Plug 'ap/vim-css-color'
Plug 'tpope/vim-markdown'
Plug 'mustache/vim-mustache-handlebars'
Plug 'bmustiata/vim-cucumber'
Plug 'jparise/vim-graphql'
Plug 'zchee/vim-flatbuffers'
Plug 'uarun/vim-protobuf'
Plug 'mfukar/robotframework-vim'
Plug 'hashivim/vim-terraform'

" autocomplete
Plug 'prabirshrestha/asyncomplete.vim'
" Plug 'prabirshrestha/vim-lsp'
Plug 'bmustiata/vim-lsp'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'thomasfaingnaert/vim-lsp-snippets'
Plug 'thomasfaingnaert/vim-lsp-ultisnips'

" core final init
Plug 'file://.vim/plugged/zzzgespace'
Plug 'file://.vim/plugged/zzzciplogic'

call plug#end()

