snippet c "Add a comment"
#
# ${VISUAL}${0:}
#
endsnippet

#
# snippet: cs
# w (word boundary),
# m (trim spaces on the right of the script)
# Add a comment section
#
snippet cs "Add a comment section" wm
#======================================
# ${VISUAL}${0:}
#======================================
endsnippet
