FROM python:3.8

COPY ./requirements.txt /src/requirements.txt
RUN cd /src && \
    pip install -r requirements.txt

COPY . /src

WORKDIR /src

ENV PYTHONPATH=. SERVER_MODE=production

EXPOSE 7000

ENTRYPOINT ["uvicorn", "--host", "0.0.0.0", "--port", "7000", "{{arg0}}.mainapp:app"]
