layout:
  name: MiniConda Python Layout
  requires: [MINICONDA_HOME]
  activate: |
    OLDDIR=$(pwd)
    cd $MINICONDA_HOME/bin/
    pwd
    . activate
    cd $OLDDIR

    ps1-show python
  deactivate: |
    OLDDIR=$(pwd)
    cd $MINICONDA_HOME/bin/
    . deactivate
    cd $OLDDIR
  commands:
    cdb: cd $MINICONDA_HOME/bin

