hi! link NERDTreeExecFile GeFsExecutable
hi! link NERDTreeDir GeFsDirectory
hi! link NERDTreeNodeDelimiters GeFsDirectory
hi! link NERDTreeOpenable GeFsDirectory
hi! link NERDTreeClosable GeFsDirectory
hi! link NERDTreeUp GeBlue4Italic
hi! link NERDTreeLinkFile GeFsDirectoryLink
hi! link NERDTreeLinkTarget GeFsExecutableLinkTarget
hi! link NERDTreeHelp GeComment
