hi! link NERDTreeExecFile GeFsExecutable
hi! link NERDTreeDir GeFsDirectory
hi! link NERDTreeNodeDelimiters GeFsDirectory
hi! link NERDTreeOpenable GeFsDirectory
hi! link NERDTreeCloseable GeFsDirectory
hi! link NERDTreeUp GeFsDirectoryLink
hi! link NERDTreeLinkFile GeFsDirectoryLink
hi! link NERDTreeLinkTarget GeFsExecutableLinkTarget
hi! link NERDTreeHelp GeComment
